"""
Santa Clara University

COEN 240 - Machine Learning

Final Project

Quan Bach
Anh Truong


By running thi file: 
    - a plot of documents embedding will be shown in plots-tab
    - the plot will also be saved in the current working directory      
    
*** NOTICE ***: this script will dowload the 20 news group dataset from sklearn and perform processing directly here before the lda models. 
Therefore, it does not used the vocabularies generated by other files previously. However, the content should be the same. 


"""
from sklearn.datasets import fetch_20newsgroups
from yellowbrick.text import TSNEVisualizer
from sklearn.feature_extraction.text import TfidfVectorizer



if __name__ == '__main__':
    
    print('Loading dataset...')
    print('...')
    # load data 
    newsgroups_train = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'), shuffle = True)    
    print('20 news group data set loaded...')
    print ('...')
    
    print('t-SNE in progress...')
    print('...')
    # get ready for t-SNE
    tfidf  = TfidfVectorizer()
    docs   = tfidf.fit_transform(newsgroups_train.data)
    labels = newsgroups_train.target
    
    # create the visualizer
    tsne = TSNEVisualizer()
    tsne.fit(docs, labels)
    tsne.show(outpath="docuEmbedding.png")
    tsne.poof()
    
